// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpP51EzIsE8nNTDFilK31csbRwTGBBEU',
    appId: '1:253338075803:web:ac3823a7235f5cb9317c3e',
    messagingSenderId: '253338075803',
    projectId: 'sein-lae-myay',
    authDomain: 'sein-lae-myay.firebaseapp.com',
    databaseURL: 'https://sein-lae-myay.firebaseio.com',
    storageBucket: 'sein-lae-myay.appspot.com',
    measurementId: 'G-L1EW2W0WS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHfosIpSTZP22yAKha92dM2UBYrIdTkQ',
    appId: '1:253338075803:android:c649d020b30bf4d4317c3e',
    messagingSenderId: '253338075803',
    projectId: 'sein-lae-myay',
    databaseURL: 'https://sein-lae-myay.firebaseio.com',
    storageBucket: 'sein-lae-myay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYyFxXBg6M_jyj-o4KHgNkCSBFuw2t4M',
    appId: '1:253338075803:ios:e82a728b021a4411317c3e',
    messagingSenderId: '253338075803',
    projectId: 'sein-lae-myay',
    databaseURL: 'https://sein-lae-myay.firebaseio.com',
    storageBucket: 'sein-lae-myay.appspot.com',
    iosBundleId: 'com.example.firebaseAdvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYyFxXBg6M_jyj-o4KHgNkCSBFuw2t4M',
    appId: '1:253338075803:ios:f85e0c7c88778960317c3e',
    messagingSenderId: '253338075803',
    projectId: 'sein-lae-myay',
    databaseURL: 'https://sein-lae-myay.firebaseio.com',
    storageBucket: 'sein-lae-myay.appspot.com',
    iosBundleId: 'com.example.firebaseAdvanced.RunnerTests',
  );
}
